# Default values for payment-order.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  hostIP: 9.42.20.35
  Name: e-commerce-solution
  namespace: kubernetesnamespace
  Profile: docker

customer-info:
  Name: customer-info
  Image: "customer-infoImageName"
  Port: 32399

batch:
  Name: inventory
  Image: "inventoryImageName"
  Port: 32400

order-info:
  Name: order-info
  Image: "order-infoImageName"
  Port: 32408

payment:
  Name: payment
  Image: "paymentImageName"
  Port: 32401

product-catalog:
  Name: product-catalog
  Image: "product-catalogImageName"
  Port: 32402

recommendation:
  Name: recommendation
  Image: "recommendationImageName"
  Port: 32403

return-and-refunds:
  Name: return-and-refunds
  Image: "return-and-refundsImageName"
  Port: 32410

review:
  Name: review
  Image: "reviewImageName"
  Port: 32404

shipping:
  Name: shipping
  Image: "shippingImageName"
  Port: 32409

shopping-cart:
  Name: shopping-cart
  Image: "shopping-cartImageName"
  Port: 32405

wishlist:
  Name: wishlist
  Image: "wishlistImageName"
  Port: 32406